### ISSUE TITLE
What does retry return on error?

### ISSUE THREAD

**Issue by Narigo** [webpapaya/promise-frites#17]
The documentation doesn't show it and the tests currently only check for `error`, making me wonder whether that's the first or last error that got thrown.

It might make sense to add a test that shows which error happened when `retry` rejected. Maybe even a list of errors instead of only one?

**Comment by webpapaya** [comment]
Returning a list of errors sounds like a good idea. I'll look into this in the next week.

**Comment by webpapaya** [comment]
In version v1.0.2 Retry now throws a RetryError where one can access the other errors like that:

```js
const error = new Error('API example error');
const apiCall = () => { throw error };
const retry3Times = retry(3);
Promise.resolve()
 .then(retry3Times(apiCall))
 .then((value) => console.log(value))
 .catch((retryError) => {
   console.log(retryError.errors[0] === error); // true
   console.log(retryError.errors[1] === error); // true
   console.log(retryError.errors[2] === error); // true
 });
```

- https://github.com/webpapaya/promise-frites/blob/master/doc.md#retry
